website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Tovar, Basket, Order
from . import db
import json
from collections import defaultdict
from sqlalchemy import func

views = Blueprint('views', __name__)

@views.route('/')
def catalog():
    tovar_list = Tovar.query.all()
    return render_template('catalog.html', tovar_list=tovar_list, user=current_user)

@views.route('/AddTovar')
def adminAddTovar():
    return render_template('AddTovar.html', user=current_user)

@views.route('/AddSklad')
def adminAddSklad():
    return render_template('AddSklad.html', user=current_user)

@views.route('/product/<name>')
def product(name):
    tovar = Tovar.query.filter_by(name=name).first()
    if tovar is None:
        return render_template('error.html'), 404
    return render_template('product.html', tovar=tovar, user=current_user)

@views.route('/basket')
@login_required
def basket():
    user_email = current_user.email
    items = Basket.query.filter_by(user_email=user_email).all()
    
    basket_price = round(sum(item.price for item in items), 2)
    all_basket_price = basket_price + 5
    
    return render_template('basket.html', items=items, user=current_user, basket_price=basket_price, all_basket_price=all_basket_price)

@views.route('/remove_item', methods=['POST'])
@login_required
def remove_item():
    data = json.loads(request.data)
    id = data['id']
    
    item = Basket.query.get(id)
    
    if item:
        if item.user_email == current_user.email:
            db.session.delete(item)
            db.session.commit()
            return jsonify({"message": "Товар удален из корзины"})
        else:
            return jsonify({"error": "Вы не можете удалить этот товар"})
    else:
        return jsonify({"error": "Товар не найден"})  
    
@views.route('/myOrders')
@login_required
def myOrders():
    orders = Order.query.filter_by(email=current_user.email).all()
    order_dict = defaultdict(list)
    order_prices = {}

    for order in orders:
        order_dict[order.nomerzakaza].append(order)
        if order.nomerzakaza not in order_prices:
            first_order = Order.query.filter_by(nomerzakaza=order.nomerzakaza).first()
            order_prices[order.nomerzakaza] = first_order.obsh_price
    return render_template('myOrders.html', order_dict=order_dict, user=current_user, order_prices=order_prices)

website/templates/AddSklad.html
{% extends "base.html" %}
{% block title %}Добавление склада{% endblock %}
{% block content %}
<div class = "fon">
  <div class="form-container">
    <form method="POST" class="login-reg-box">
      <h2 style="color: black; padding: 15px; margin: 0 5 0 0; text-align: center;">Add Sklad</h2>
      <input
        type="text"
        class="form-control"
        id="street"
        name="street"
        placeholder="Enter adress"
      />
      <div style = "text-align: center;">
        <button type="submit" class = "custom-btn btn-16">Add</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

website/templates/AddTovar.html
{% extends "base.html" %}
{% block title %}Добавление товара{% endblock %}
{% block content %}
<div class = "fon"> 
  <div class="form-container" >
    <form method="POST" class="login-reg-box">
      <h2 style="color: black; padding: 15px; margin: 0 5 0 0; text-align: center;">Add Tovar</h2>
      <input
        type="text"
        class="form-control"
        id="name"
        name="name"
        placeholder="Enter name"
      />
      <input
        type="text"
        class="form-control"
        id="cost"
        name="cost"
        placeholder="Enter cost"
      />
      <input
        type="text"
        class="form-control"
        id="material"
        name="material"
        placeholder="Enter material"
      />
      <input
        type="text"
        class="form-control"
        id="type_of_decoration"
        name="type_of_decoration"
        placeholder="Enter type of decoration"
      />
      <input
        type="text"
        class="form-control"
        id="opisanie"
        name="opisanie"
        placeholder="Enter opisanie"
      />
      <div style = "text-align: center;">
        <button type="submit" class = "custom-btn btn-16">Add</button>
      </div>
    </form>
  </div>  
</div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <title>{% block title %}Base{% endblock %}</title>
</head>
  <body>
    <header class="fixed-header">
      <div class="header-content">
          <div class="left-content">
            <span class="store-name">marlboro</span>
            <a id="menu-button" style = "padding-right: 50px;">
              <img src="{{ url_for('static', filename='img/menu.png')}}" width = 20 height = 20 alt="Меню">
            </a>
            <nav>
              <ul>
                  <li onclick="window.location.href='/'">Каталог товаров</li>                      
                  <li onclick="window.location.href='/myOrders'" >Заказы</li>
                  <li
                    {% if user.is_authenticated %}
                    {{ user.first_name }}
                  {% else %}
                    Аккаунт 
                  {% endif %}
                    {% if user.is_authenticated %}
                      <li onclick="window.location.href='/logout'">Выйти</li>
                      {% if user.email == 'admin@gmail.com' %}
                        <li onclick="window.location.href='/AddTovar'">Добавить Товар</li>
                        <li onclick="window.location.href='/AddSklad'">Добавить Склад</li>
                      {% endif %}
                    {% else %}
                      <li onclick="window.location.href='/login'">Войти</li>
                      <li onclick="window.location.href='/sign-up'">Зарегистрироваться</li>
                    {% endif %}
                  </li>
              </ul>
          </nav>
          </div>
          <div class="right-content">
              <nav>
                  <ul>
                    <li onclick="window.location.href='/basket'">
                      <img src="{{ url_for('static', filename='img/basket_black.png')}}" width = 50 height = 50 alt="Корзина">
                  </li>
                  </ul>
              </nav>
          </div>
      </div>
    </header>
    <main>

      {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert {% if category == 'error' %}alert-danger{% else %}alert-success{% endif %} alert-dismissable fade show custom-alert" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

      <div class="cont" style = "width: 100%;">
        {% block content %} 
        {% endblock %}
      </div>

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous" ></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous" ></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

      {% block javascript %}
        <script type="text/javascript">
          function deleteItem(id) {
            fetch("/remove_item", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({ id: id })
            }).then((response) => {
                if (response.ok) {
                    window.location.reload();
                } else {
                    console.error("Ошибка при удалении товара");
                }
            });
        }
        </script>
        <script type="text/javascript">
          var timeoutId = null;
          function increaseQuantity(itemId) {
            clearTimeout(timeoutId);
            var input = document.getElementById('kol-' + itemId);
            var currentQuantity = parseInt(input.value, 10);
            var currentPriceInput = document.getElementById('price-' + itemId);
            var currentPrice = parseFloat(currentPriceInput.value);
            var alone_price = currentPrice / currentQuantity;
            input.value = currentQuantity + 1;
            var newPrice = currentPrice + alone_price;
          
            var formattedPrice = newPrice.toFixed(2);
            currentPriceInput.value = formattedPrice;
            updateQuantityOnServer(itemId, input.value, formattedPrice);
          
            timeoutId = setTimeout(function () {
              location.reload();
            }, 1000); 
          }   
          
          function decreaseQuantity(itemId) {
            clearTimeout(timeoutId);
            var input = document.getElementById('kol-' + itemId);
            var currentQuantity = parseInt(input.value, 10);
            var currentPriceInput = document.getElementById('price-' + itemId);
            var currentPrice = parseFloat(currentPriceInput.value);
            var alone_price = currentPrice / currentQuantity;
            if (currentQuantity > 1) {
              input.value = currentQuantity - 1;
              var newPrice = currentPrice - alone_price;
          
              var formattedPrice = newPrice.toFixed(2);
              currentPriceInput.value = formattedPrice;
              updateQuantityOnServer(itemId, input.value, formattedPrice);

              timeoutId = setTimeout(function () {
                location.reload();
              }, 1000);
            }
          }
          function updateQuantityOnServer(itemId, quantity, price) {
            fetch('/update-quantity', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                itemId: itemId,
                quantity: quantity,
                price: price,
              }),
            });
          }
        </script>
      {% endblock %}


  </main>
    <footer>
      <div class = "fot_cont_text">
              <div onclick="window.location.href=' '">Политика конфиденциальности</div>
              <div onclick="window.location.href=' '">Договор оферты</div>
              <div onclick="window.location.href=' '">Дополнительная информация</div>
      </div>
      <div class = "fot_cont_img">
          <a href="">
              <img src="{{ url_for('static', filename='img/TikTok.png')}}" width="20" height="20" alt="Изображение 1">
          </a>
          <a href="">
              <img src="{{ url_for('static', filename='img/twitter.png')}}" width="20" height="20" alt="Изображение 2">
          </a>
          <a href="">
              <img src="{{ url_for('static', filename='img/instagram.png')}}" width="20" height="20" alt="Изображение 3">
          </a>
      </div>
  </footer>
  </body>
</html>

website/templates/basket.html
{% extends "base.html" %}

{% block title %}Корзина{% endblock %}

{% block content %}
<div style = "margin: 120px 0px 0px 0px; ">
    <div class = "contbasket"> 
        <div class = "OpisB1">
            <h2 style = "padding: 5px;">Корзина</h2>
                <hr style = "background: rgb(131, 131, 131); width: 100%;">
                    <ul class="list-group">
                    {% for item in items %}
                        <li class="list-group-item" style="background: white;">
                            <div style = "display: flex; align-items: center; justify-content: space-between;">
                                <div style="display: flex; align-items: center;">
                                    <img src="{{ url_for('static', filename='img/' + item.tovar_name + '.jpg') }}" alt="{{ item.tovar_name }}" width="100">
                                    <div class="ml-3" style="font-size: 16px; text-align:center; vertical-align: middle;">
                                        <div>{{ item.tovar_name }}</div>
                                        <div style = "padding-top: 11px;">({{ item.size }})size</div>
                                        <input id="price-{{ item.id }}" type="text" value="{{ item.price }} руб." style="outline: none; background:rgb(216, 241, 255); color: black; border: black; width: 120px; height: 30px; text-align: center; margin-bottom: 0px; font-size: 16px; text-align: center; vertical-align: middle;" readonly>         
                                      </div>
                                </div>
                                <div  style="text-align:center; vertical-align: middle; padding: 0">                       
                                    <input id="kol-{{ item.id }}" type="text" value="{{ item.quantity }}" style="margin: 10px; background:rgb(216, 241, 255); color: black; border: white; width: 40px; height: 30px; text-align: center; font-size: 16px; text-align: center; vertical-align: middle;" readonly>         
                                </div> 
                                <div> 
                                    <button type="button" style="margin: 0; padding: 0; color: black; background:rgb(216, 241, 255); border: 0 black; font-size: 30px; text-align: center; vertical-align: middle;" onClick="deleteItem({{ item.id }})">×</button>
                                </div>
                            </div>  
                        </li>
                        <hr style = "background: rgb(131, 131, 131);" >
                    {% endfor %}
                    </ul>      
        </div>

        <div class = "OpisB2">
            <form method="POST">
                <h2 style = "padding: 5px;">Оформление заказа</h2>
                <br>
                <p class = "mainT">Телефон</p>
                    
                <input 
                    type="text"
                    id="telephone"
                    name="telephone"
                    style = "background: white; color: black; border: 1px solid grey; height: 36px; width: 100%; padding: 0px 20px; font-size: 16px;"
                    placeholder="Номер телефона"
                /> 



                <br>
                <p class = "mainT">Получатель</p>
                <input
                    type="text"
                    id="fio"
                    name="fio" 
                    style = "background: white; color: black; border: 1px solid grey; height: 36px; width: 100%; padding: 0px 20px; font-size: 16px;" 
                    placeholder="Иванов Иван Иванович"
                />       
                
                <p class = "mainT">Адрес</p>
                    
                <input
                    type="text"
                    id="city"
                    name="city" 
                    style = "background: white; color: black; border: 1px solid grey; height: 36px; width: 100%; padding: 0px 20px; font-size: 16px;"
                    placeholder="Город"
                />   
                <input
                    type="text"
                    id="adress"
                    name="adress" 
                    style = "background: white; color: black; border: 1px solid grey; height: 36px; width: 100%; padding: 0px 20px; font-size: 16px;" 
                    placeholder="Улица дом, квартира"
                /> 
        
                <p class = "mainT">Комментарий</p>

                <input
                    type="text"
                    id="coment"
                    name="coment" 
                    style = "background: white; color: black; border: 1px solid grey; height: 36px; width: 100%; padding: 0px 20px; font-size: 16px;" 
                    placeholder="Комментарий к заказу"
                />          
        
                    <p class = "mainT">Промокод</p>

                <input
                    type="text"
                    id="promocod"
                    name="promocod" 
                    style = "background: white; color: black; border: 1px solid grey; height: 36px; width: 100%; padding: 0px 20px; font-size: 16px;" 
                    placeholder="Введите промокод (если имеется)"
                />          
                
                <p class = "mainT">Доставка</p>


                <div class="contradio">
                    <input type="radio" disabled>
                    <div style="font-size: 16px;">Доставка по миру<span class = "inoeT"> от 7 дней 5 руб.</span></div>
                </div>
              
                    <div class = "basketCostContener"> 
                        <div>Сумма:                             
                            {{basket_price}} руб.
                        </div>
                        <p>Доставка по миру: 5 руб.</p>
                        <div>Итоговая сумма: {{all_basket_price}} руб.</div>
                    </div>      
                    
                    {% for item in items %}
                        <input type="hidden" id="obsh_price" name="obsh_price" value="{{ item.price }}">
                        <input type="hidden" id="tovar_name" name="tovar_name" value="{{ item.tovar_name }}">
                        <input type="hidden" id="tovar_quantity" name="tovar_quantity" value="{{ item.quantity }}">
                    {% endfor %}

                    <button type="submit" style="background-color: #28cbff; color: black; margin-bottom: 120px; font-size: 24px; border-radius: 0; border: 0px;  align-items: center; width: 100%; height: 50px;">Оформить заказ</button>
            </form>  
        </div>
    </div>
</div>  
{% endblock %}

website/templates/catalog.html
{% extends "base.html" %}
{% block title %}Сайт для продажи украшений{% endblock %}
{% block content %}
    

    <div id="blackContainer" style = "top: 120px;">
      <div class="container mt-4 d-flex justify-content-center align-items-center">
        <div id = "1" class="row" style = "justify-content: center;">


          {% for tovar in tovar_list %}
              <div class="tovar_box">
                <div style = "text-align: center; ">
                  <a href="{{ url_for('views.product', name=tovar.name) }}"> 
                    <img style = "" src="{{ url_for('static', filename='img/' + tovar.name + '.jpg') }}" class="card-img-top productIMG" alt="{{ tovar.name }}">
                  </a>
              </div>
            
            <div style="padding: 13px 20px 10px 20px; color: black;">
              <span>{{ tovar.name }} <span style = "background:#28cbff; color: black; font-size: 13px; padding: 0 3px 0 3px; margin: 0  0 0 10px">new</span> </span> 
              <div>{{ tovar.cost }} руб.</div>
            </div>
          </div>
      {% endfor %}


        </div>
      </div>
    </div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Вход {% endblock %}
{% block content %}
<div class = "fon">
  <div class="form-container">
    <form method="POST" class="login-reg-box">
      <h2 style="color: black; padding: 15px; margin: 0 5 0 0; text-align: center;">Войти</h2>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Введите почту"
      />
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Введите пароль"
      />
      
      <div style = "text-align: center;">
        <button type="submit" class = "custom-btn btn-16">Войти</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

website/templates/myOrders.html
{% extends "base.html" %}
{% block title %}Заказы{% endblock %}
{% block content %}
<div class = "fon">
    <div class="container">
        {% for nomerzakaza, orders in order_dict.items() %}
        <div class="card mb-3" style = "top: 120px;     background-color: rgba(255, 255, 255, 0.26);
        backdrop-filter: blur(10px);
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); border: 0;">
            <div class="card-header text-center" >
                <h2 class="card-title">Заказ #{{ nomerzakaza }}</h2>
                <p class="card-price">Общая цена: {{ order_prices[nomerzakaza] }} руб.</p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th style="color:black; text-align: center;">Товар</th>
                                <th style="color:black; text-align: center;">Размер</th>
                                <th style="color:black; text-align: center;">Количество</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <td>
                                    <div style="color:black;">
                                        <img class = "imgSize" src="{{ url_for('static', filename='img/' + order.tovar_name + '.jpg') }}" style="width: 200px; height: 150px;"  alt="img">
                                        <span class="ml-2">{{ order.tovar_name }}</span>
                                    </div>
                                </td>

                                <td style="color:black; text-align:center; vertical-align: middle;">
                                    {{ order.tovar_size }}
                                </td>
                            
                                <td style="color:black; text-align:center; vertical-align: middle;">
                                    {{ order.tovar_quantity }}
                                </td>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/product.html
{% extends "base.html" %}

{% block title %}{{tovar.name}}{% endblock %}

{% block content %}

    <div class="contProd" style="margin-top: 120px;">
        <div class="imgPrCont">
            <div class="scroll-container1">
                <img style="margin: 25px 0 0 80px; border: 1px solid rgba(255, 255, 255, 0.26);
                background: white;
                backdrop-filter: blur(10px); box-shadow: -5px 5px 10px 10px rgba(156, 156, 156, 0.486);" 
                     src="{{ url_for('static', filename='img/' + tovar.name + '.jpg') }}" 
                     class="productIMG" alt="img">
            </div>
        </div>
        <div class="Opis">
            <h2>{{tovar.name}}</h2>
            <p class="inoeT">{{tovar.type_of_decoration}}</p>
            <br>
            <hr style="background: rgb(131, 131, 131);">
            <br>
            <button onclick="changeCount(-1)" class="plus_minus_count">-</button>
            <input id="countInput" type="text" value="1" style="  background-color: rgb(231, 241, 247);  color: black; border-radius: 0; border: 1.3px solid gray; width: 60px; height: 30px; text-align: center; margin-bottom: 0px;"
    readonly>
            <button onclick="changeCount(1)" class="plus_minus_count">+</button>
            <br>
            <br>
                <div>
                    <button class="size-button" onclick="selectSize(this)">15</button>
                    <button class="size-button" onclick="selectSize(this)">15.5</button>
                    <button class="size-button" onclick="selectSize(this)">16</button>
                    <button class="size-button" onclick="selectSize(this)">16.5</button>
                    <button class="size-button" onclick="selectSize(this)">17</button>
                    <button class="size-button" onclick="selectSize(this)">17.5</button>
                    <button class="size-button" onclick="selectSize(this)">18</button>
                    <button class="size-button" onclick="selectSize(this)">18.5</button>
                    <button class="size-button" onclick="selectSize(this)">19</button>
                    <button class="size-button" onclick="selectSize(this)">19.5</button>
                    <button class="size-button" onclick="selectSize(this)">20</button>
                    <button class="size-button" onclick="selectSize(this)">20.5</button>
                    <button class="size-button" onclick="selectSize(this)">21</button>
                    <button class="size-button" onclick="selectSize(this)">21.5</button>
                    <button class="size-button" onclick="selectSize(this)">22</button>
                    <button class="size-button" onclick="selectSize(this)">22.5</button>
                    <button class="size-button" onclick="selectSize(this)">23</button>
                </div>
            <br>
            <p class="mainT">Описание</p>
            <p class="inoeT">{{tovar.opisanie}}</p>

            <p class="mainT">Характеристики</p>
            <div><span class="inoeT">Материал</span> - {{tovar.material}}</div>
            <br>
            <form action="/add_to_basket" method="post">
                <input type="hidden" name="selectedSizeInput" id="selectedSizeInput" value="">
                <input type="hidden" name="tovar_name" value="{{ tovar.name }}">
                <input type="hidden" name="count" id="countInputHidden" value="1">
                <input type="hidden" name="total_cost" id="total_cost_input" value="{{ tovar.cost }}">

                <button type="submit"
                    style="background-color: #28cbff; color: black; padding: 10px; border-radius: 0; border: 0px; display: flex; justify-content: space-between; align-items: center; width: 100%; height: 50px;">
                    <span style="margin-right: auto;">Добавить в корзину</span>
                    <span id="total_cost">{{ tovar.cost }} руб.</span>
                </button>
            </form>
        </div>
    </div>
    <script>
        var count = 1;
        var tovarCost = {{ tovar.cost }};

        function changeCount(delta) {
            var countInput = document.getElementById('countInput');
            var countInputHidden = document.getElementById('countInputHidden');
            var totalCostSpan = document.getElementById('total_cost');
    
            var currentCount = parseInt(countInput.value);
            var newCount = currentCount + delta;
    
            if (newCount >= 1) {
                countInput.value = newCount;
                countInputHidden.value = newCount;
    
                var newTotalCost = newCount * tovarCost;
                totalCostSpan.innerText = newTotalCost.toFixed(2) + ' руб.';
            }
        }

        function selectSize(button) {
            var buttons = document.querySelectorAll('.size-button');
            buttons.forEach(function (btn) {
                btn.classList.remove('selected');
            });

            button.classList.add('selected');
            var selectedSizeInput = document.getElementById('selectedSizeInput');
            selectedSizeInput.value = button.innerText;
        }
    </script>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<div class = "fon">
  <div class="form-container">
    <form method="POST" class="login-reg-box">
      <h2 style="color: black; padding: 15px; margin: 0 5 0 0; text-align: center;">Регистрация</h2>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Введите почту"
      />
      <input
        type="text"
        class="form-control"
        id="nickname"
        name="nickname"
        placeholder="Введите имя"
      />
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Введите пароль"
      />
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2"
        placeholder="Подтвердите пароль"
      />
      <div style = "text-align: center;">
        <button type="submit" class = "custom-btn btn-16">Создать</button>
      </div>
    </form>
  </div>  
</div>
{% endblock %}